export const stateList = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Federated States Of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const memberType = [
  " Resident",
  "Medical Student",
  "Green Card Backlog",
  "Young Physician (YPS) (First 10 years in practice)",
];

export const memberSubType = ["Annual", "Patron(Life)"];

export const primarySpecialtyOrDegree = [
  "BDS",
  "DDS",
  "DO",
  "MBBS",
  "MD",
  "MDS",
  "MPH",
  "MS",
  "PhD",
  "MBA",
  "JD",
];

export const secondarySpeciality = [
  "Addiction Medicine",
  "Aerospace Medicine",
  "Allergy &amp; Immunology",
  "Alternative Medicine",
  "Anesthesiology",
  "Cardiac surgery",
  "Cardiovascular Diseases",
  "Child Psychiatry",
  "Chiropractic",
  "Colon &amp; Rectal Surgery",
  "Critical Care (Intensivists)",
  "Dentist",
  "Dermatology",
  "Diagnostic Radiology",
  "Emergency Medicine",
  "Endocrinology",
  "Family Medicine",
  "Forensic Medicine",
  "Gastroenterology",
  "General Practice",
  "General Surgery",
  "Geriatric Medicine",
  "Gynecological oncology",
  "Gynecology",
  "Hand surgery",
  "Hematology",
  "Hematology/Oncology",
  "Hospitalist",
  "Infectious disease",
  "Internal Medicine",
  "Maxillofacial surgery",
  "Medical Oncology",
  "Neonatology",
  "Nephrology",
  "Neurological Surgery",
  "Neurology",
  "Neuropsychiatry",
  "Neuro-Radiology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Obstetrics &amp; Gynecology",
  "Occupational Medicine",
  "Ophthalmology",
  "Optometry",
  "Oral surgery",
  "Orthopedic Surgery",
  "Other Specialty",
  "Otolaryngology",
  "Pain Management",
  "Palliative Care",
  "Pathology",
  "Pediatric Cardiology",
  "Pediatric Endocrinology",
  "Pediatric Hematology/Oncology",
  "Pediatric Nephrology",
  "Pediatric Radiology",
  "Pediatric Surgeon",
  "Pediatrics",
  "Physical Medicine &amp; Rehabilitation",
  "Plastic Surgery",
  "Podiatry",
  "Psychiatry",
  "Public Health",
  "Pulmonary Diseases",
  "Pulmonary/Critical Care",
  "Radiation Oncology",
  "Radiology Interventional",
  "Reconstructive surgery",
  "Rehabilitation Medicine",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Surgical oncology",
  "Thoracic Surgery",
  "TransplantSurgery",
  "Undecided",
  "Urology",
  "Vascular Surgery",
  "Family Medicine/Family Practice",
  "Obstetrics &amp; Gynecology",
  "Allergy &amp; Immunology",
  "Critical Care Surgery",
  "Trauma Surgery",
  "Physical Medicine &amp; Rehabilitation",
  "Endocrinology, Nuclear Medicine",
  "Gynecology, Obstetrics &amp; Gynecology",
  "Colon &amp; Rectal Surgery",
  "Cytopathology",
  "Anesthesiology, Pain Management",
  "Internal Medicine, Family Medicine",
  "Radiology",
  "Pulmonary Diseases, Critical Care (Intensivists)",
  "Internal Medicine, Geriatric Medicine",
  "Geriatric Medicine, Sleep Medicine",
  "Sleep Medicine, Internal Medicine",
  "Hospice &amp; Palliative Medicine",
  "Hospice &amp; Palliative Medicine (Emergency Medicine)",
  "Epilepsy &amp; Neurophysiology",
  "Infectious Disease Medicine",
  "Developmental-Behavioral Pediatrics",
  "Orthopedic Hand Surgery",
  "Oncology",
  "Anatomic &amp; Clinical Pathology",
  "Surgery",
  "Obstetrics &amp; Gynecology, Forensic Medicine",
  "Emergency Medicine, Geriatric Medicine",
  "Neonatal Medicine",
  "Reproductive Endocrinology &amp; Infertility",
  "Gynecologic Surgery",
  "Child &amp; Adolescent Psychiatry",
  "General Medicine, Pediatrics",
  "Internal Medicine, Nuclear Medicine",
  "Hematology/Oncology, Palliative Care",
  "Emergency Medicine, General Surgery",
  "Preventive Occupational Medicine",
  "Phlebology",
  "Ear, Nose, and Throat",
  "Cardiology",
  "Critical Care (Intensivists), Sleep Medicine",
  "Nuclear Radiology",
  "Geriatric Medicine, Internal Medicine",
  "Family Medicine, Gynecology",
  "Diagnostic Radiology, Nuclear Medicine",
  "Cosmetic Surgery",
  "Internal Medicine, Oncology",
  "Sleep Medicine, Nuclear Medicine",
  "Pain Medicine",
  "Oncology, Internal Medicine",
  "General Surgery, Family Medicine",
  "Palliative Care, Internal Medicine",
  "Independent Medical Examiner",
  "Orthopedic Hand Surgery, Plastic Surgery of the Hand",
  "Internal Medicine, Hematology",
  "Internal Medicine, Critical Care (Intensivists)",
  "Endocrinology, Diabetes &amp; Metabolism",
  "Undersea &amp; Hyperbaric Medicine",
  "Family Medicine, Geriatric Medicine",
  "Critical Care Medicine",
  "Cosmetic Surgery, General Surgery, Plastic &amp; Reconstructive Surgery,",
  "plastic Surgery of the Hand",
  "Pulmonary Disease, Sleep Medicine",
  "Medical Oncology, Hematology",
  "Emergency Medicine, Pediatrics",
  "Pain Management, Critical Care (Intensivists)",
  "Vascular &amp; Interventional Radiology",
  "Transplant Surgery",
  "Interventional Cardiology",
  "Pain Management, Addiction Medicine",
  "Nuclear Medicine, Occupational Medicine",
  "Bariatric Surgery",
  "Vascular Surgery, Colon &amp; Rectal Surgery",
  "Pulmonary/Critical Care, Internal Medicine",
  "Internal Medicine, Interventional Cardiology",
  "Pediatric Neurology",
  "Transplant Hepatology",
  "Pulmonary/Critical Care, Sleep Medicine",
  "Internal Medicine, Medical Oncology",
  "Internal Medicine, Pain Management",
  "Hematology &amp; Oncology",
  "Clinical Cardiac Electrophysiology",
  "General Practice, Internal Medicine",
  "Geriatric Medicine, Palliative Care",
  "Cardiovascular &amp; Pulmonary Diseases",
  "Pulmonary Disease",
  "Neurological Movement Disorders",
  "Pediatric Critical Care Medicine",
  "Cardiovascular Diseases, Internal Medicine",
  "Pediatric Hematology/Oncology, Pediatrics",
  "Internal Medicine, Cardiovascular Diseases",
  "Pain Management, Palliative Care, Public Health",
  "Cardiovascular Interventional Technology",
  "Transplant Surgery, Internal Medicine",
  "Critical care",
  "Sleep Medicine, Pulmonary Diseases",
  "General Medicine, Geriatric Medicine",
  "Geriatric Medicine, Critical Care (Intensivists)",
  "Pain Management, Sleep Medicine",
  "Cosmetic &amp; Reconstructive Surgery, General Surgery",
  "Pediatric Neurosurgery",
  "Anterior Segment Ophthalmology, Cornea &amp; External Diseases",
  "Rheumatology, Geriatric Medicine",
  "Breast Surgery",
  "Breast Oncology, General Surgery",
  "Pediatrics, Pulmonary Diseases",
  "Dentistry",
  "Transplant Surgery, Surgical oncology",
  "Neurotology, Otolaryngic Allergy, Sinus Surgery",
  "Sleep Medicine, Palliative Care",
  "Adult &amp; Adolescent Psychiatry, Geriatric Psychiatry",
  "Internal Medicine, Pulmonary Disease",
  "Internal Medicine, Transplant Nephrology",
  "Other Specialty, Hematology",
  "Orthodontics",
  "Pediatric Ophthalmology",
  "Psychiatry, Sleep Medicine",
  "Pediatric Surgeon, Public Health",
  "Hospitalist, Internal Medicine",
  "Oncology, Colon &amp; Rectal Surgery",
  "Addiction Medicine, Geriatric Medicine",
  "Addiction Medicine, Pain Management",
  "Infectious disease, Internal Medicine",
  "Maternal-Fetal Medicine",
  "Cardiothoracic Surgery",
  "Pulmonary Diseases, Sleep Medicine",
  "Critical Care (Intensivists), Pulmonary Diseases",
  "Hematology/Oncology, Internal Medicine",
  "Nephrology, Internal Medicine",
  "Hospitalist, Infectious disease",
  "Neuropsychiatry, Public Health",
  "Sports Medicine, Reconstructive surgery",
  "Diagnostic Radiology, Radiology Interventional",
  "Critical Care (Intensivists), Infectious disease",
  "Family Medicine, Emergency Medicine",
  "Public Health, Palliative Care, Geriatric Medicine",
  "General Surgery, Colon &amp; Rectal Surgery",
  "Cardiac surgery, Thoracic Surgery",
  "Surgical oncology, Urology, Plastic Surgery",
  "Internal Medicine, Hospitalist",
  "Family Medicine, Hospitalist",
  "Hematology, Medical Oncology",
  "Dentist, Oral surgery, Other Specialty",
  "Urology, Alternative Medicine, Addiction Medicine",
  "Critical Care (Intensivists), Pulmonary/Critical Care",
  "Endocrinology, Medical Oncology",
  "Anesthesiology, Pediatrics",
  "Pulmonary Diseases, Internal Medicine",
  "Hospitalist, Palliative Care",
  "None",
  "Family Medicine, Palliative Care",
  "Plastic Surgery, Sleep Medicine",
  "Surgical oncology, General Surgery",
  "Internal Medicine, Emergency Medicine",
  "Transplant Surgery, General Surgery",
  "Hospitalist, Cardiovascular Diseases",
  "Neonatoloty",
  "Transplant nephrology",
  "Intermal Medicine",
  "Radiation Onclogy",
  "Urogynecology",
  "Pediatrics Critical Care",
  "Hospital Medicine",
  "Medicine",
  "Infertious Disease",
  "Professor",
  "Obstetrics &amp;amp; Gynecology",
  "Obstetrics &amp;amp; Gynecology, Forensic Medicine",
];

export const gender = ["male", "female"];

export const region = [
  "Pacific - Alaska, California, Hawaii, Oregon and Washington",
  "Mountain - Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah and Wyoming",
  "Northwest Central - Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota and South Dakota",
  "Southwest Central - Arkansas, Louisiana, Oklahoma and Texas",
  "Northeast Central I - Illinois, Indiana, and Wisconsin",
  "Northeast Central II - Michigan and Ohio",
  "Southeast Central - Alabama, Kentucky, Mississippi and Tennessee",
  "New England - Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island and Vermont",
  "Mid Atlantic I - New York",
  "Mid Atlantic II - New Jersey and Pennsylvania",
  "South Atlantic - Delaware, District of Columbia, Maryland, Virginia and West Virginia",
  "South - North Carolina, South Carolina, Georgia and Florida",
];

export const practiceType = [
  "Academic",
  "Administrative",
  "Hospital Full time",
  "Private Practice",
  "Research",
  "Retired",
];

export const organization = [
  "Academic Pediatric Association",
  "Academy of General Dentistry",
  "Accelerated Cure Project for Multiple Sclerosis",
  "American Academy of Allergy, Asthma and Immunology",
  "American Academy of Audiology",
  "American Academy of Child and Adolescent Psychiatry",
  "American Academy of Facial Plastic and Reconstructive Surgery",
  "American Academy of Family Physicians",
  "American Academy of Neurology",
  "American Academy of Ophthalmology",
  "American Academy of Optometry",
  "American Academy of Pediatrics",
  "Amritsar Medical &amp; Dental Alumni Association of North America",
  "Association of Kerala Medical Graduates",
  "Benaras Hindu University Alumni Association",
  "BJ Medical College Alumni Association",
  "Bombay University Medical Alumni",
  "Maulana Azad Medical College Alumni Asnn of North America",
  "Osmania University Medical Alumni Association of America",
  "SVMC Alumni of USA",
  "MOCAAPI (Monmouth &amp; Ocean County NJ Chapter of AAPI)",
  "AAPI Oklahoma Chapter",
  "AAPI Queens &amp; Long Island Inc",
  "AAPI Westchester NY",
  "AAPI Wisconsin",
  "Alabama Association of Physicians of Indian Origin",
  "Arizona Association of Physicians of Indian Origin",
  "Association of Indian Physicians of Cincinnati",
  "Association of Indian Physicians of Northern Ohio",
  "Brevard Indian Medical &amp; Dental Association",
  "Doctors of South Asia",
  "Hudson Valley Association of Physicians from India (NY)",
  "Indian Medical Council of Greater St. Louis",
  "Indian Medical Society of New Jersey",
  "Indian Physicians of Florida",
  "Indian Physicians Association of Central California",
  "Michigan Association of Physicians of Indian Origin",
  "Texas Indo-American Physicians Society Central Chapter",
  "Texas Indo-American Physicians Society NW Chapter",
  "Texas Indo-American Physicians Society NE Chapter",
  "Texas Indo-American Physicians Society SW Chapter",
  "Treasure Coast Indo-American Physicians Physicians Society in India",
  "Tri State Association of Physicians of Indian Origin",
  "American Association of Otolaryngologists of Indian Heritage",
  "Association of Asian Indians in Ophthalmology",
  "Indian American Urological Association",
  "Indian Dental Association of California",
  "The Federation of AAPI of Greater NY &amp; NJ",
  "IMA of Greater Los Angeles",
  "Terre Haute American Association of Physicians of Indian Origin",
  "Florida Association of Physicians of Indian Origin",
  "Mohawk Valley Indian Physician Organization",
  "American Society of Indian Anesthesiologist",
  "Association of Allergists &amp; Immunologists from India",
  "Indian Doctors Association of Houston",
  "Society of Orthopedic Surgeons of India in North America",
  "Federation of Andhra Pradesh Medical Graduates in USA",
  "AAPI Mid South",
  "American Association of Cardiologists",
  "IAMA Charitable Foundation",
  "AIIMSONIANS of America",
  "Armed Forces Alumni Association of North America",
  "Association of Maharashta Physicians of America",
  "Association of Tamilnadu Medical Graduates USA",
  "Baroda Medical College Alumni Association",
  "Butler &amp; Allegheny Med Society Physicians of Asian Indian Origin",
  "Gems of America",
  "Guntur Medical College",
  "Gajra Raja Medical College Alumni Association",
  "Karnataka State Medical &amp; Dental Alumni Association of America",
  "Kasturba Medical College Alumni Association of USA",
  "King George Medical College Alumni Association of North America",
  "Lady Harding Medical College Alumni Association",
  "Nagpur Government Medical College Alumni",
  "Patiala Medical College Alumni Association of North America",
  "Rajasthan Medical Alumni Association",
  "Rangaraya Medical College Alumni of North America",
  "San Diego Association of Physicians of Indian Origin",
  "St. John's Medical College Alumni Association",
  "AAPI Northeast Ohio &amp; Western Pennsylvania",
  "AAPI Rockford-Westchester County NY",
  "AAPI Bronx",
  "AAPI Central New Jersey",
  "AAPI of Central Ohio",
  "AAPI Colorado/Wyoming",
  "AAPI Dayton",
  "AAPI Downstate Illinois",
  "AAPI Hudson County NJ",
  "AAPI Kansas",
  "AAPI Lehigh County PA",
  "AAPI Louisiana",
  "AAPI Manhattan",
  "AAPI Maryland Chapter",
  "AAPI Mid South TN",
  "AAPI Midwest Nebraska",
  "AAPI Mississippi",
  "AAPI Mohawk Valley NY",
  "AAPI New Mexico",
  "AAPI New York (Staten Island)",
  "AAPI Northern California",
  "AAPI of Northwest New Jersey",
  "AAPI Philadelphia",
  "AAPI Tennessee",
  "Asian America Physicians Association of Western NY",
  "Association of America Physicians from South Asia",
  "Association of Indian Physicians of Indiana",
  "Chattanooga Asn of Physicians From India",
  "Connecticut Association of Physicians &amp; Dentists of Indian Origin",
  "Georgia Association of Physicians from India",
  "IMA of Northwest Indiana",
  "IMANE (New England)",
  "Indian Medical Association of Southern California",
  "Indian America Medical Association of Greater Wash DC",
  "Indian American Medical Association of Illinois",
  "Indian Medical Association of Greater Los Angeles",
  "Indian Physician Association of Greater Canton",
  "Virginia Association of American Physicians of Indian Origin",
  "Indo-American Medical Forum",
  "Kentucky Association of Indian Physicians",
  "Miami Valley Association of Physicians from India",
  "Nevada Association of Physicians of Indian Origin",
  "North Carolina Association of Physicians of Indian Origin",
  "Palm Beach India Medical Association",
  "Physicians of India-Genessee, Lapeer &amp; Shiawassee",
  "Texas Indo-American Physicians Society State Level",
  "Texas Indo-American Physicians Society SE Chapter",
  "Tri Valley Indian Medical Association (California)",
  "Tri-State Association of Physicians of Indian Origin (PA,NJ,NY)",
  "Virginia Society of Physicians of Indian Origin, Inc.",
  "Washington Association of Physicians of Indian Origin",
  "Association of Indian Physicians in America",
  "American Association of Cardiologists of Indian Origin",
  "American Association of Gastroenterologists of Indian Origin",
  "American Association of Indian Anesthesiologists",
  "American Association of Physicians &amp; Dentists of India",
  "American Association of Radiologists of Indian Origin",
  "Association of Indian Pathologists in North America",
  "Foundation of Physicians for Pediatric &amp; Perinatal Care",
  "Indian-US Biomedical Research Foundation",
  "Indo-American Psychiatric Association",
  "Society of Asian Indian Surgeons in North America",
  "American Association of Otolaryngologist",
  "AAPI Essex County NJ",
  "American Academy for Emergency Medicine",
  "AACPIO",
  "Oncology Center of SW PA",
  "South Carolina Association of Physicians",
  "Association of Indian Neurologist in America",
  "Connecticut Association of Physicians of Indian Origin",
  "Greater Charlotte Association of Physicians of India",
  "MPMAANA (Madhya Pradesh Medical Alumni Association in North America)",
  "American College of Cardiology",
  "American Heart Association",
  "Medical Society of New Jersey (MSNJ)",
  "American College of Surgeons",
  "American Academy of Otolaryngology-Head and Neck Surgery",
  "PGI MER",
  "American College of Physicians",
  "AAPI East",
  "American Academy of Pain Medicine",
  "American Academy of Physical Medicine &amp; Rehabilitation",
];

export const addressType = ["Mailing", "Billing", "Other", "Home", "Work"];

export const state = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District Of Columbia",
  "Federated States Of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Islands",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const phoneType = [
  "Cell",
  "Fax",
  "Home",
  "Home Office",
  "Office",
  "Office2",
  "Pager",
];

export const medicalSchoolName = [
  "Andhra Medical College",
  "Dr. N.T.R. University of Health Sciences",
  "Government Medical College, Anantapur",
  "Gandhi Institute of Technology and Management",
  "Guntur Medical College",
  "Katuri Medical College",
  "Kurnool Medical College",
  "Narayan Medical College and Hospital",
  "NRI Medical College",
  "PES Institute of Medical Sciences and Research",
  "Rangaraya Medical College",
  "Rajiv Gandhi Institute of Medical Sciences",
  "Siddhartha Medical College",
  "Sri Sathya Sai Institute of Higher Medical Sciences",
  "Great Eastern Medical School and Hospital",
  "Assam Medial College",
  "Fakhruddin Ali Ahmed Medical College",
  "Guwahati Medical College",
  "Jorhat Medical College and Hospital",
  "Silchar Medical College and Hospital",
  "Tezpur Medical College and Hospital",
  "All India Institute of Medical Sciences - Patna",
  "Indira Gandhi Institute of Medical Sciences",
  "Patna Medical College and Hospital",
  "Nalanda Medical College Hospital",
  "Darbhanga Medical College and Hospital",
  "Sri Krishna Medical College",
  "A N Magadh Medical College and Hospital",
  "Jawaharlal Nehru Medical College",
  "Katihar Medical College",
  "Narayan Medical College and Hospital",
  "Post Graduate Institute of Medical Education and Research",
  "All India Institute of Medical Science - Raipur",
  "Pt. Jawahar Lal Nehru Memorial Medical College",
  "Lt.Shri Lakhiram Agrawal Memorial Medical College",
  "Goa Medical College",
  "Baroda Medical College",
  "B.J. Medical College, Ahmedabad",
  "Government Medical College, Surat",
  "M. P. Shah Medical College",
  "Pandit Deendayal Upadhyay Medical College",
  "Bhagat Phool Singh Medical College",
  "Kalpana Chawla Government Medical College",
  "Maharaja Agrasen Medical College",
  "Maharishi Markandeshwar Institute of Medical Sciences and Research",
  "Pt. B.D. Sharma PGIMS Rohtak",
  "Shaheed Hasan Khan Mewati Government Medical College",
  "Shree Guru Gobind Singh Tricentenary University",
  "Government Medical College, Srinagar",
  "Sher-i-Kashmir Institute of Medical Sciences",
  "Mahatma Gandhi Memorial Medical College, Jamshedpur",
  "Rajendra Institute of Medical Sciences",
  "Pataliputra Medical College",
  "Al-Ameen Medical College",
  "Bangalore Medical College and Research Institute",
  "Father Muller Medical College",
  "Government Ayurveda Medical College and Hospital",
  "Jawaharlal Nehru Medical College",
  "JSS medical college",
  "Karnataka Institute of Medical Sciences",
  "Kasturba Medical College",
  "Kasturba Medical College",
  "Kempegowda Institute of Medical Sciences",
  "Khaja Banda Nawaz Institute of Medical Sciences",
  "KS Hegde Medical Academy&nbsp;Mangalore",
  "Mysore Medical College",
  "National Institute of Mental Health and Neurosciences",
  "Rajarajeswari Medical College and Hospital",
  "S. S. Institute of Medical Sciences",
  "Shimoga Institute of Medical Sciences",
  "St John's Medical College",
  "Vijayanagara Institute of Medical Sciences",
  "Vydehi Institute of Medical Sciences and Research Centre",
  "Amala Institute of Medical Sciences",
  "Amritha Institute Of Medical Sciences",
  "Azeezia Medical College",
  "Government Medical College, Kozhikode",
  "Dr. Somervell Memorial CSI Medical College",
  "Employee's State Insurance Corporation Medical College Hospital",
  "Government Medical College, Manjeri",
  "Government Medical College, Thrissur",
  "Government T D Medical College",
  "Jubilee Mission Medical College and Research Institute",
  "Government Medical College, Kottayam",
  "Pushpagiri Medical College",
  "Travancore Medical College Hospital",
  "Government Medical College, Thiruvananthapuram",
  "Cooper Hospital&nbsp;and H.B.T. Medical College",
  "King Edward Memorial Hospital and Seth Gordhandas Sunderdas Medical College",
  "Topiwala National Medical College&nbsp;(BYL Nair Charitable Hospital)",
  "Lokmanya Tilak Municipal General Hospital&nbsp;(Municipal hospital and medical college)",
  "Grant Medical College",
  "B. J. Medical College, Pune",
  "Rajiv Gandhi Medical College",
  "Government Medical College, Latur",
  "Dr. V. M. Government Medical College",
  "Shri Bhausaheb Hire Government Medical College",
  "Government Medical College, Nagpur",
  "Government Medical College, Akola",
  "R.C.S.M. Govt Medical College and CPR Hospital",
  "Dr. Shankarrao Chavan Government Medical College",
  "Shri Vasantrao Naik Government Medical College",
  "Government Medical College, Aurangabad",
  "Government Medical College, Chandrapur",
  "ACPM Medical College",
  "Armed Forces Medical College",
  "Mahatma Gandhi Institute of Medical Sciences",
  "Maharashtra Institute of Medical Science and Research",
  "Maharashtra Institute of Medical Education and Research",
  "All India Institute of Medical Science - Bhopal",
  "Gandhi Medical College",
  "Shyam Shah Medical College",
  "Gajara Raja Medical College",
  "Mahatma Gandhi Memorial Medical College, Indore",
  "Netaji Subhash Chandra Bose Medical College",
  "People's Medical College",
  "R.D. Gardi Medical College",
  "Jawaharlal Nehru Institute of Medical Sciences",
  "Regional Institute of Medical Sciences",
  "North Eastern Indira Gandhi Regional Institute of Health and Medical Sciences",
  "All India Institute of Medical Sciences - New Delhi",
  "Army College of Medical Sciences",
  "University College of Medical Sciences",
  "Maulana Azad Medical College",
  "Lady Hardinge Medical College",
  "Post Graduate Institute of Medical Education and Research (New Delhi)",
  "Vardhman Mahavir Medical College",
  "All India Institute of Medical Sciences - Bhubaneswar",
  "Shri Ramachandra Bhanj Medical College",
  "MKCG Medical College and Hospital",
  "Kalinga Institute of Medical Sciences",
  "Institute of Medical Sciences and Sum Hospital",
  "Hi-Tech Medical College &amp; Hospital",
  "Hi-Tech Medical College",
  "Mahatma Gandhi Medical College &amp; Research Institute",
  "Government Medical College, Amritsar",
  "Government Medical College, Patiala",
  "Christian Medical College",
  "Adesh Institute of Medical Sciences &amp; Research",
  "Guru Gobind Singh Medical College",
  "Punjab Institute of Medical Sciences",
  "Dayanand Medical College",
  "Pacific Medical College and Hospital",
  "Geetanjali Medical College&nbsp;and Hospital",
  "Dr. S.N. Medical College",
  "SMS Medical College",
  "Rabindranath Tagore Medical College",
  "Sardar Patel Medical College",
  "Jawaharlal Nehru Medical College",
  "Government Medical College, Kota",
  "Jhalawar Medical College",
  "All India Institute of Medical Science - Jodhpur",
  "Sikkim Manipal Institute of Medical Sciences",
  "Thanjavur Medical College",
  "Madras Medical College&nbsp;and Research Institute",
  "Stanley Medical College",
  "Government&nbsp;Kilpauk Medical College",
  "Chengalpattu Medical College",
  "Madurai Medical College",
  "Coimbatore Medical College",
  "Tirunelveli Medical College",
  "Mohan Kumaramangalam Medical College",
  "K.A.P.Viswanatham Government Medical College",
  "Government Vellore Medical College",
  "Christian Medical College",
  "Government Theni Medical College",
  "Thoothukudi Medical College",
  "Government Villupuram Medical College",
  "Government Thiruvarur Medical College",
  "Government Sivgangai Medical College",
  "Government Siddha Medical College - Chennai",
  "Government Homeopathy Medical College - Madurai",
  "Government Ayurveda Medical College",
  "Government Unani Medical College",
  "Government Yoga &amp; Naturopathy Medical College&nbsp;Arumbakkam",
  "Deccan College of Medical Sciences",
  "Gandhi Medical College, Hyderabad",
  "Government Medical College, Nizamabad",
  "Government Nizamia Tibbi College",
  "Kakatiya Medical College",
  "Kamineni Institute of Medical Sciences",
  "Malla Reddy Institute of Medical Sciences",
  "Mamata Medical College",
  "Mediciti Institute Of Medical Sciences",
  "Osmania Medical College",
  "Rajiv Gandhi Institute of Medical Sciences",
  "Shadan Institute of Medical Sciences",
  "Rajiv Gandhi Institute of Medical Sciences",
  "Subharti Medical College, Swami Vivekananda Subharti University",
  "Faizabad Medical College",
  "Rohilkhand Medical College",
  "Shri Ram Murti Smarak Institute of Medical Sciences",
  "King George's Medical University(KGMU)",
  "Institute of Medical Sciences, Banaras Hindu University",
  "Baba Raghav Das Medical College, Deen Dayal Upadhyay Gorakhpur University",
  "Ganesh Shankar Vidyarthi Memorial Medical College",
  "Jawaharlal Nehru Medical College, Aligarh Muslim University",
  "Lala Lajpat Rai Memorial Medical College",
  "Rajkiya Alopathic Medical College",
  "Maharani Laxmi Bai Medical College",
  "Motilal Nehru Medical College",
  "Muzaffarnagar Medical College",
  "Uttar Pradesh University of Medical Sciences",
  "Sanjay Gandhi Post Graduate Institute of Medical Sciences",
  "Sarojini Naidu Medical College",
  "Government Medical College, Jalaun",
  "Government Medical College, Azamgarh",
  "Kansiram medical college",
  "Santosh Medical college",
  "Netaji Subhash Chandra Bose Subharti Medical college",
  "Saraswati Medical College",
  "Government Medical College, Kannauj",
  "Glocal Medical College",
  "All India Institute of Medical Science - Rishikesh",
  "Government Medical College, Haldwani",
  "Government Medical College, Srinagar",
  "Shri Guru Ram Rai Institute of Medical &amp; Health Sciences",
  "Swami Rama Himalayan University&nbsp;",
  "Malda Medical College and Hospital",
  "Sagar Dutta Memorial Medical College and Hospital",
  "Medical College Kolkata",
  "R. G. Kar Medical College and Hospital",
  "Nil Ratan Sarkar Medical College and Hospital",
  "Calcutta National Medical College",
  "North Bengal Medical College",
  "Burdwan Medical College",
  "Bankura Sammilani Medical College",
  "IPGME&amp;R and SSKM Hospital",
  "KPC Medical College and Hospital",
  "Midnapore Medical College and Hospital",
  "College Of Medicine &amp; JNM Hospital",
  "Murshidabad Medical College",
  "SV Medical College",
  "University of Alabama School of Medicine",
  "University of South Alabama College of Medicine",
  "American University of Antigua",
  "Arizona Neurological Institute",
  "University of Arizona College of Medicine",
  "University of Arkansas for Medical Sciences College of Medicine",
  "Keck School of Medicine of the University of Southern California",
  "Loma Linda University School of Medicine",
  "Stanford University School of Medicine",
  "University of California, Davis, School of Medicine",
  "University of California, Irvine, School of Medicine",
  "University of California, Los Angeles David Geffen School of Medicine",
  "University of California, San Diego School of Medicine",
  "Western University School of Medicine",
  "Windsor University",
  "American University of Carrebian",
  "St. Matthews University",
  "University of Colorado School of Medicine",
  "Ross University School of Medicine",
  "Yale University School of Medicine",
  "George Washington University School of Medicine and Health Sciences",
  "Georgetown University School of Medicine",
  "Howard University College of Medicine",
  "S.S.R. Medical College",
  "The University of Manchester",
  "Florida State University College of Medicine",
  "Nova Southeastern University",
  "University of Central Florida College of Medicine",
  "University of Florida College of Medicine",
  "University of Miami Leonard M. Miller School of Medicine",
  "University of South Florida College of Medicine",
  "Emory University School of Medicine",
  "Medical College of Georgia School of Medicine",
  "Mercer University School of Medicine",
  "Morehouse School of Medicine",
  "St. George's University",
  "University of Hawaii, John A. Burns School of Medicine",
  "Semmelweis Medical",
  "University of Debrecen",
  "Chicago Medical School at Rosalind Franklin University of Medicine &amp; Science",
  "Loyola University Chicago Stritch School of Medicine",
  "Northwestern University The Feinberg School of Medicine",
  "Rush Medical College of Rush University Medical Center",
  "Southern Illinois University School of Medicine",
  "St James School of Medicine",
  "University of Chicago Division of the Biological Sciences The Pritzker School of Medicine",
  "University of Illinois College of Medicine",
  "Indiana University School of Medicine",
  "Des Moines University College of Osteopathic Medicine",
  "University of Iowa Roy J. and Lucille A. Carver College of Medicine",
  "University of Osteopathic Medicine And Health Sciences",
  "The University of the West Indies",
  "University of West Indies",
  "Makerere Medical University",
  "University of Kansas School of Medicine",
  "University of Louisville School of Medicine",
  "University of Nairobo",
  "Amrita Institute of Medical Sciences",
  "Louisiana State University School of Medicine in New Orleans",
  "Louisiana State University School of Medicine in Shreveport",
  "Tulane University School of Medicine",
  "University of East Manila",
  "Johns Hopkins University School of Medicine",
  "University of Maryland School of Medicine",
  "Boston University School of Medicine",
  "Harvard Medical School",
  "New England College of Optometry",
  "Saba University School of Medicine",
  "Tufts University School of Medicine",
  "University of Massachusetts Medical School",
  "SSR Medical College",
  "Universidad Iberoamericana",
  "Michigan State University College of Human Medicine",
  "Michigan State University College of Osteopathic Medicine",
  "University of Michigan Medical School",
  "Wayne State University School of Medicine",
  "Kansas City University of Medicine",
  "Saint Louis University School of Medicine",
  "University of Missouri-Columbia School of Medicine",
  "University of Missouri-Kansas City School of Medicine",
  "University of Missouri-Kansas School of Dentistry",
  "Washington University in St. Louis School of Medicine",
  "Creighton University School of Medicine",
  "University of Nebraska College of Medicine",
  "University of Nevada School of Medicine",
  "Medical University of the Americas",
  "Dartmouth Medical School",
  "UMDNJ-SOM",
  "University of Medicine and Dentistry of New Jersey-New Jersey Medical School",
  "University of Medicine and Dentistry of New Jersey-Robert Wood Johnson Medical School",
  "University of New Mexico School of Medicine",
  "Albany Medical College",
  "Albert Einstein College of Medicine of Yeshiva University",
  "Columbia University College of Physicians and Surgeons",
  "Cornell University",
  "Mount Sinai School of Medicine of New York University",
  "New York College of Osteopathic Medicine",
  "New York Medical College",
  "New York University School of Dentistry",
  "New York University School of Medicine",
  "Robert Wood Johnson Medical School",
  "State University of New York Downstate Medical Center College of Medicine",
  "State University of New York Upstate Medical University",
  "Stony Brook University School of Medicine (State University of New York)",
  "Suny Medical School",
  "SUNY-Downstate",
  "The School of Medicine at Stony Brook University Medical Center",
  "University at Buffalo State University of New York School of Medicine &amp; Biomedical Sciences",
  "University of Rochester School of Medicine and Dentistry",
  "Upstate Medical University",
  "Weill Cornell Medical College",
  "Duke University School of Medicine",
  "University of North Carolina at Chapel Hill School of Medicine",
  "Case Western Reserve University School of Medicine",
  "Northeastern Ohio Universities Colleges of Medicine and Pharmacy",
  "Ohio State University College of Medicine",
  "The University of Toledo College of Medicine",
  "University of Cincinnati College of Medicine",
  "University of Toledo",
  "Oklahoma University College of Medicine",
  "University of Oklahoma College of Medicine",
  "Schulich School Of Medicine At The University Of Western Ontario",
  "Oregon Health &amp; Science University School of Medicine",
  "Drexel University College of Medicine",
  "Jefferson Medical College of Thomas Jefferson University",
  "Lake Erie Colege of osteopathic Medicine",
  "Pennsylvania State University College of Medicine",
  "Philadelphia College of Osteopathic Medicine",
  "Temple University School of Medicine",
  "University of Pennsylvania School of Medicine",
  "University of Pittsburgh School of Medicine",
  "Medical University of Lodz",
  "Medical University of Lublin",
  "Medical University of Silesia",
  "Medical University of Silesia, Poland",
  "McGill University Medical School",
  "Warren Alpert Medical School of Brown University",
  "UNIBE School of Medicine",
  "University of Seychelles",
  "Chandka Medical College",
  "University of the Witwatersrand, Johannesburg, South Africa",
  "Flinders University of South Australia, School of Medicine",
  "Medical University of South Carolina College of Medicine",
  "University of South Carolina School of Medicine",
  "Spartan University of Health Sciences",
  "Sackler School of Medicine",
  "Meharry Medical College",
  "Vanderbilt University School of Medicine",
  "Baylor College of Medicine",
  "Texas A&amp;M Health Science Center College of Medicine",
  "Texas Tech University Health Sciences Center School of Medicine",
  "University of Texas Medical Branch School of Medicine",
  "University of Texas Medical School at Houston",
  "University of Texas School of Medicine at San Antonio",
  "University of Texas Southwestern Medical Center at Dallas Southwestern Medical School",
  "Dundee University , Scotland, Great Britain, U.K.",
  "Guy's and St. Thomas's Medical School",
  "University of Manchester",
  "Medical College of Virginia",
  "University of Virginia School of Medicine",
  "VCOM Osteopathic School",
  "Virginia Commonwealth University School of Medicine",
  "University of Washington School of Medicine",
  "Medical College of Wisconsin",
  "University of Wisconsin School of Medicine and Public Health",
  "Bhaskar Medical School",
  "Government Medical College",
  "International University of Health Sciences",
  "Jawaharlal Nehru Medical College",
  "KLE Societys Jawaharlal Nehru Medical College",
  "Medical College",
  "Pt. Jawaharlal Nehru Medical College",
  "Govt Medical College",
  "Government Medical College, Bhavnagar",
  "Smt. NHL Municipal Medical College",
  "Seth GS Medical College",
  "Topiwala National Medical College",
  "Gandhi Medical College, Bhopal",
  "Case Western Reserve University",
  "University of Bombay",
  "Tulane Medical School",
  "Mahatma Gandhi Missions Medical College, Navi Mumbai",
  "Trenton University",
  "University Of Mumbai Medical School",
  "Seth Gs Medical College, Maharashtra University Of Health Sciences Medical School",
  "Dr. Vaishampayan Memorial Government Medical College",
  "Overlook Hospital",
  "Jawaharlal Institute of Post Graduate Medical Reseach (JIPMER), Pondicherry",
  "M.P. Shah Medical College",
  "Grant Med Coll-Bombay U Medical School",
  "Grant Medical College, Maharashtra University Of Health Sciences Medical School",
  "GSVM Medial College",
  "U Bombay Medical School",
  "Bangalore Medical College",
  "University of London",
  "RG Kar Medical College",
  "University of Chicago",
  "Gunter Medical College",
  "Medical College, Kolkata",
  "Gajra Raja Medical College",
  "American College of Colon and Rectal Surgeons",
  "American Board of Pediatrics",
  "United Hospitals Medical Center",
  "St. John's Medical College",
  "Oregon Health &amp; Science University",
  "King George's Medical University, Lucknow",
  "Sawai Man Singh Medical College (SMS)",
  "MGM Medical College",
  "Christian Medical College, Ludhiana, Baba Farid University Of Health Sciences Medical School",
  "Christian Medical College, Ludhiana",
  "Christian Medical College, Vellore",
  "Philadelphia VA Medical Center",
  "American Board of Surgery",
  "Baptist Hospital",
  "Andhra Medical College",
  "Howard University Hospital",
  "University of Connecticut Health Center",
  "Institute Of Medical Sciences, Banaras Hindu UniversityMedical School",
  "Patna Medical College",
  "New York University",
  "American College of Chest Physician",
  "Assam Medical College",
  "Post Graduate Institute of Medical Education and Research, Chandigargh",
  "Universidad Tecnologica De Santiago, Santo Domingo Campus Medical School",
  "Brooklyn Methodist Hospital",
  "Government Dental College and Hospital",
  "Chicago Medical School at Rosalind Franklin University of Medicine Science",
  "Saint Joseph Hospital",
  "Chicago Medical School",
  "United Hospital Internal Medicine",
  "St George's University",
  "Trivandrum Medical College",
  "Armed Forces Medical College, Pune",
  "Fairview General Hospital",
  "University of Miami",
  "New Jersey Medical School",
  "Kasturba Medical College, Manipal",
  "Children's Hospital of Pittsburgh",
  "Nalanda Medical College",
  "Kasturba Medical College, Mangalore",
  "American College of Surgeons",
  "RNT Medical College",
  "Norwich Hospital",
  "Dayanand Medical College &amp; Hospital",
  "Irwin Hospital",
  "American College of Obstetricians &amp; Gynecologists",
  "Jawaharlal Institute Of Post-Graduate Medicine Research, Pondicherry University",
  "American College of Cardiology",
  "SUNY Upstate Med Univ Medical School",
  "American College of Physicians",
  "Sri Ramachandra Medical College",
  "St. Vincent's Hospital, New York",
  "Cornell Medical Center",
  "Misericord Community Hospital",
  "Muni Med Coll, Gujarat U",
  "T. D. Medical College",
  "Government Medical College, Miraj",
  "Lokmanya Tilak Municipal Medical College",
  "Jawaharlal Nehru Medical College, Belgaum",
  "SUNY Downstate Medical Center",
  "JJM Medical College",
  "Mahadevappa Rampure Medical College",
  "Our Lady of Mercy Medical Center",
  "Saint Joseph Hospital, Flint, Michigan",
  "Weill Cornell Medical Center",
  "Hawaii Kuakini Hospital, Honolulu",
  "Norwich University",
  "Bergen Regional Medical Center",
  "University of California, Davis",
  "All-India Institute Of Medical Sciences",
  "Jawaharlal Institute Of Post-Graduate Medicine Research, Pondicherry University Medical School",
  "LLRM Medical College",
  "MS Ramaiah Medical College",
  "Punjabi University / Government Medical College Medical School",
  "Government Medical College Mysore, Rajiv Gandhi University Of Health Sciences Medical School",
  "Rutgers New Jersey Medical School",
  "Jackson Memorial Hospital",
  "Rohtak Medical College",
  "University Of Michigan Medical School Medical School",
  "Government Medical College, Jammu",
  "Umdnj-New Jersey Med Sch",
  "People's Medical College",
  "University Of Texas Medical School",
  "Cook County Hospital",
  "Indira Gandhi Medical College, Shimla",
  "Mahatma Gandhi Missions Medical College, Aurangabad",
  "St Louis Univ Sch Of Med Medical School",
  "Sri Devaraj Urs Medical College",
  "Clinical Health Systems",
  "VSS Medical College",
  "Seth G.S. Medical College/Kem Hospital Medical School",
  "Armed Forces Medical College, Maharashtra University Of Health Sciences Medical School",
  "Institute of Post Graduate Medical Education And Research",
  "Metropolitan College",
  "Jawaharlal Nehru Medical College, Ajmer",
  "Jawaharlal Nehru Medical College, Wardha",
  "Krishna Institute of Medical Sciences",
  "Bharati Vidyapeeth Medical",
  "Postgraduate Inst. of Med. Education and Research",
  "PSG Institute of Medical Sciences",
  "Brooklyn Hospital Center",
  "BLDE University",
  "Guru Govind Singh Medical College",
  "Rural Medical College",
  "Jawaharlal Nehru Medical College, Aligarh",
  "Texas Tech University",
  "Dayanand Medical College and Hospital",
  "University Of Miami / School Of Medicine Medical School",
  "Texas A &amp; M Health Science Center College of Medicine",
  "American University of the Caribbean School of Medicine",
  "Government Dental College",
  "Patna Dental College and Hospital",
  "Manipal University",
  "Pramukhswami Medical College",
  "Adichunchanagiri Institute of Medical Sciences",
  "Louisiana State University",
  "Geisinger Health System",
  "K.J. Somaiyya Medical College",
  "University Of Birmingham Medical School",
  "Nair Hospital Dental College",
  "University Of Miami / School Of Medicine",
  "UT Southwestern Medical Center",
  "Government College of Indian Medicine",
  "Lady Hardinge Medical College / University Of Delhi Medical School",
  "Armed Forces Medical College, Pune University Medical School",
  "Government Medical College Guru Nanak Dev University",
  "Gnd U Medical School",
  "All-India Institute Of Medical Sciences, All-India Institute Of Medical Sciences Medical School",
  "Sriram Chandra Bhanja Medical College, Utkal University Medical School",
  "Maharashtra Institute of Medical Sciences &amp; Research, Latur",
  "Dr Sn Medical College, University Of Rajasthan Medical School",
  "St George's University Medical School",
  "Albany Med Coll Medical School",
  "Shri Bhausaheb Hire Government Medical College, Dhule",
  "Indiana University",
  "University of California, Irvine, CA",
  "Wayne State University School Of Medicine Medical School",
  "Grace University Medical School",
  "Mysore Medical College Medical School",
  "Duke University Medical School",
  "Dr. Panjabrao alias Bhausaheb Deshmukh Memorial Medical College",
  "M P Shah Medical College, Saurashtra University Medical School",
  "Joan C. Edwards School of Medicine at Marshall University",
  "Dr. D. Y. Patil Medical College",
  "University of Wisconsin Affiliated Hospital",
  "Baba Farid University of Health Sciences",
  "Jawahar Lal Nehru Medical College",
  "University at Buffalo State University of New York School of Medicine &amp; Biomedical Sciences",
  "Dr. B.R. Ambedkar Medical College",
  "Rajah Muthiah Medical College",
  "Oregon Health &amp; Science University School of Medicine",
  "Thomas Jefferson University Hospitals",
  "NDMVP Samaj's Medical College",
  "University of Oklahoma",
  "Indira Gandhi Medical College &amp; Hospital",
  "Guy's and St. Thomas's Medical School",
  "Government Medical College, Bellary",
  "University of the West Indies",
  "University of Mississippi Medical Center",
  "Dundee University, Scotland",
  "Lokmanya Tilak Mun Mc Bombay U Medical School",
  "SVS Medical College",
  "Gandhi Medical College",
  "Veer Surendra Sai Institute of Medical Sciences and Research",
  "Smt. N.H.L.M. Medical",
  "St. Johns Medical College",
  "KVGMC, India",
  "JNMC, Belgaum, Karnataka",
  "University of Minnesota School of Dentristry",
  "Sri Venkateswara Medical College Tirupati",
  "University of MS Medical Center",
  "J.N.M.C. Belgaum/ UMC Jackson",
  "Bhavnagar Medical College, Gujarat",
  "Mysore Medical College, Karnataka",
  "SV Medical College Tirupati",
  "Dr Vaishampayan Memorial Medical School",
  "Govt. Medical College, Rajkot",
  "Shri BM Patil Medical College",
  "Terna Medical College",
  "Texas College of Osteopathic Medicine",
  "Universidad Autónoma de Guadalajara",
  "Lincoln Memorial University-DeBusk College of Osteopathic Medicine",
  "Liberty University College of Osteopathic Medicine",
  "R. G. Kar Medical College and Hospital",
  "V.S. Dental College",
  "Arizona College of Osteopathic Medicine",
  "University of Tennessee College of Medicine",
  "University of Cambridge",
  "Wright State University",
  "Other",
  "University of California San Francisco",
  "Universidad Autonoma de Ciudad Juarez (UACJ), Mexico",
  "Marquette University Dental School",
  "Charles E. Schmidt College of Medicine Florida Atlantic University",
  "Dr Baba Sahib Ambedkar Medical College and Hospital",
  "Midwestern University Chicago College of Osteopathic Medicine",
  "PGIMS Rohtak",
  "Seth GS Medical College Mumbai",
  "Gandhi Medical College .Hyderabad",
  "Sardar Patel Medical College Bikaner, Rajasthan",
  "MP Shah Medical College",
  "St. George&amp;#39;s University",
  "NYU",
  "SP MEDICAL COLLEGE , BIKANER",
  "RNT MEDICAL COLLEGE UDAIPUR",
  "Rocky Vista University College of Osteopathic Medicine",
  "Sawai Man Singh Medical College",
  "McGill University",
  "S.P. Medical College, Bikaner",
  "Pramukh Swami Medical College",
  "Rajendra Medical College, Ranchi, India",
  "Case Western Medical",
  "UT Southwestern",
  "BJ Mediacal college",
  "Pramukshswami Medical College",
  "Kunal Gurav",
  "GRANT MEDICAL COLLEGE, MUMBAI",
  "Baroda Medical College. M.S. University",
  "SMS medical college Jaipur",
  "Madras Medical College",
  "NJMS-UMDNJ",
  "Johns Hopkins medical school",
  "Nova Southeastern University College of Osteopathic Medicine",
  "GSCS",
  "Government medical college, Amritsar, Punjab",
  "Smt N.H.L medical college",
  "SGRD Institute of Medical Sciences and Research",
  "Mahatma Gandhi Memorial Medical College",
  "NYCOM",
  "Rush",
  "GANDHI MEDICAL COLLEGE, HYDERABAD, INDIA",
  "M P Shah Medical College",
  "University of Pittsburgh",
  "Northeastern Ohio Medical University",
  "Guru Gobind Singh Medical College, India.",
  "Windsor University School of Medicine",
  "Ross University",
  "Chandka Medical College, Larkana, Pakistan",
  "Topiwala Nathional Medical School",
  "Government Medical College, Nagpur, India",
  "GGS medical college Faridkot,",
  "Univ College of Medical Sciences , New Delhi",
  "M S Ramaiah medical college",
  "The Ohio State University College of Medicine",
  "Narayana Medical College",
  "MGM Medical College Indore MP",
  "Siddhartha medical college/Univ. of Health sciences",
  "university of missouri kansas city",
  "Sriram Chandra Bhanj Medical college",
  "Armed Forces Media cal College",
  "S.N. Medical College",
  "INDIRA GANDHI MEICAL COLLEGE",
  "Government Medical College Chandigarh",
  "Touro College of Osteopathic Medicine",
  "NYITCOM",
  "Karntaka Institute of Medical Sciences",
  "Karntaka Institute of Medical Sciences",
  "Jnmc",
  "American University of the Caribbean, School of Medicine",
  "Kasturba Medical College, Manipal University",
  "Kasturba Medical College Mangalore",
  "MS Ramaih medical college",
  "Chirayu Medical College &amp;amp; Hospital",
  "GOVERNMENT MEDICAL COLLEGE TRICHUR ,KERALA",
  "Chicago College of Osteopathic medicine",
  "Vellore Medical College",
  "MNR medical college hospital",
  "T. N. Medical college",
  "University of Massachusetts",
  "GSVM Medical College Kanpur",
  "Grant Medical College Mumbai",
  "George Washington School of Medicine",
  "University of Tennessee health science center",
  "lake erie college of osteopathic medicine",
  "Thomas Jefferson medical college",
  "Manipal College of Medical Sciences",
  "Kasturba Medical College Manipal",
  "University of Michigan",
  "MGM Medical College, Indore, MP, India",
  "Kansas City University (KCU)",
  "JIPMER",
  "Barry University School of Podiatric Medicine",
  "Icahn School of Medicine at Mount Sinai",
  "Univ Texas Southwestern Medical School",
  "NHL Municipal Medical College",
  "Shri M. P. Shah Medical School",
  "Creighton School of Medicine",
  "University College of Medical Sciences, Delhi",
  "University of Mysore/JMM Medical College",
  "All India Institute of Medical Sciences, N Delhi",
  "JJMMC",
  "BGU",
  "KILPAUK MEDICAL COLLEGE",
  "Lady Harding Medical College",
  "JSS Medical College, Mysore",
  "Bellary Medical College",
  "Gandhi med college, Hyderabad, TS",
  "Punjab medical college faisalabad",
  "Indira Gandhi Government Medical College, Nagpur",
  "Pramukh Swami Medical College, Karamsad, Gujarat",
  "Mahatma Gandhi Mission&amp;#39;s Medical College",
  "Institute of Medical Sciences,BHU",
  "Seth G.S. Medical College",
  "smt .n.h.l. municipal medical college",
  "RNT Medicsl college Udaipur",
  "Seth G.S.Medical college",
  "Rajah Muthiah Medical College, Annamalai University",
  "Rajah Muthiah Medical College, Annamalai University",
  "Madras Dental College",
  "Baroda Medical College, Vadodara, Gujarat",
  "Baroda Medical College, Vadodara, Gujarat",
  "Government Medical College, Srinagar, J&amp;amp;K state,India",
  "MP Shah medical college Jamnagar Gujarat",
  "MP Shah medical college Jamnagar Gujarat",
  "Pramukhswami Medical college Karamsad Gujarat",
  "Pramukhswami Medical college Karamsad Gujarat",
  "Himalayan Institute of Medical Sciences, SRHU",
  "Kasturba Medical College, Manipal, Karnataka, India",
  "Kasturba Medical College, Manipal, Karnataka, India",
  "Bharati Vidyapeeth Medical School",
  "Bharati Vidyapeeth Medical School",
  "B J Medical College",
  "B.J.MEDICAL COLLEGE",
  "B.J.MEDICAL COLLEGE",
  "University of Southern California",
  "University of Southern California",
  "Konaseema institute of medical sciences &amp;amp; RF",
  "Caribbean Medical University",
  "Caribbean Medical University",
  "GMC",
  "GMC",
  "Ross University SOM",
  "Ross University SOM",
  "SRMC",
  "New York Institute of Technology College of Osteopathic Medicine at Arkansas State University",
  "Vijaynagar Institute of Medical Science",
  "International University of Health &amp;amp; Science",
  "Mahatma Gandhi Medical College and Research Institute",
  "Himalayan Institute of Medical Science, Dehradun",
  "St George&amp;#39;s University School of Medicine",
  "UCF College of medicine",
  "National University of Galway, Ireland",
  "University of Medicine and Dentistry of New Jersey",
  "Spartan Health Sciences University",
  "Avalon University School of Medicine",
  "American University of Integrative Sciences",
  "Temple University",
  "Seth GSMC and KEM Hospital, Mumbai, India",
  "Mahatma Gandhi Missions Medical collage, Mumbai",
  "mahatma gandhi mission medical college",
  "Lady Hardinge Medical College, New Delhi",
  "Windsor Medical School",
  "Amrita School of Medicine",
  "Surat Municipal Institute of Medical Education and Research",
  "ALLURI SITARAMA RAJU ACADEMY OF SCIENCES",
  "Christian Medical College, Vellore, India",
  "Smt NHL municipal Medical hospital",
  "University of California, Irvine School of Medicine",
  "Meenakshi Medical College Hospital And Research Institute",
  "C.U.Shah Medical College and Hospital",
  "Government Medical College and Hospital",
  "C.U. Shah Medical College and Hospital",
];
